links:
 phix_link: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/819/615/GCF_000819615.1_ViralProj14015/GCF_000819615.1_ViralProj14015_genomic.fna.gz
 card_link: https://card.mcmaster.ca/download/0/broadstreet-v3.2.9.tar.bz2
 checkv_link: https://portal.nersc.gov/CheckV/checkv-db-v1.5.tar.gz
directories:
  out_dir: /path/to/output_dir
  fastq_dir: /path/to/fastq_dir
  blast_db: /path/to/NCBI_core_nt
  eggnog_db: /path/to/eggnog
  gtdbtk_db: /path/to/GTDB_R220/release220
  bakta_db: /path/to/bakta/db
  platon_db: /path/to/platon/db
resources:
  threads: 25
  ram_gb: 256
parameters:
  nt_version: core_nt
  medaka_model: r1041_e82_400bps_sup_v4.3.0
  genus: